### ISSUE TITLE
GameViewController needs mention

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#14]
The GameViewController in the default SpriteKit project initializes with: SKScene not GameScene! 

Probably need to ask students to change: 

```
if let scene = SKScene(fileNamed: "GameScene")
...
```

To 

```
if let scene = GameScene(fileNamed: "GameScene") 
...
```

**Comment by dionlarson** [comment]
This is not necessary. `GameViewController` does not need to know about any of `GameScene`'s methods or properties. `GameScene.sks` will still correctly load in the custom class.
