### ISSUE TITLE
Issue with swift 3 syntax

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#2]
I get this when I build the project with Xcode 8 beta 6. slightly different syntax for didMove() and touchesBegan()

`override func didMoveToView(to view: SKView)`

vs 

`override func didMove(to view: SKView)`

and 

`override func touchesBegan(_ touches: Set<UITouch>, withEvent event: UIEvent?)`

vs

`override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?)`

Corrected code block for the last section of P1 Clean Project

```
import SpriteKit

class GameScene: SKScene {

    override func didMove(to view: SKView) {
        /* Setup your scene here */
    }

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        /* Called when a touch begins */
    }

    override func update(_ currentTime: CFTimeInterval) {
        /* Called before each frame is rendered */
    }
}
```

**Comment by esscbee** [comment]
Looks like the code was updated in 7320170f86a7a00770df89a13d47e956eea2677e - perhaps there is some sort of merge issue.

**Comment by soggybag** [comment]
Could be. I thought something was a little weird.
