### ISSUE TITLE
Scene Anchor point now in center!

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#3]
Seems the anchor point for the default scene is 0.5, 0.5! This throws the positions provided way off. See the images below. 

Solution: Ask everyone to set the anchor point of the scene to 0.0, 0.0 in the first step in section P2. 

<img width="771" alt="screen shot 2016-08-19 at 2 29 16 pm" src="https://cloud.githubusercontent.com/assets/762192/17824900/8bd5adf2-6619-11e6-8a09-3d0e5a14f436.png">
<img width="757" alt="screen shot 2016-08-19 at 2 29 34 pm" src="https://cloud.githubusercontent.com/assets/762192/17824901/8becc672-6619-11e6-9074-a344abde9ffb.png">

**Comment by esscbee** [comment]
<img width="1181" alt="screen shot 2016-08-20 at 9 42 05 am" src="https://cloud.githubusercontent.com/assets/8846585/17832550/72c39a94-66ba-11e6-96e5-48f1e6efa4cb.png">

I do not see this issue.

**Comment by soggybag** [comment]
I started the project from a new SpriteKit project in Xcode 8 beta 6, and built everything following the instructions.
