### ISSUE TITLE
Swift 3 Syntax issue Grid class

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#4]
I might have missed something but, I get a different syntax for some methods than appear in the tutorial though it looks like the tutorial was updated? 
## P3 Grid Class

The current code sample shows: 

line 21:`override func touchesBegan(_ touches: Set<UITouch>, withEvent event: UIEvent?)`

line 28:`let location  = touch.locationInNode(self)`

line 37: `userInteractionEnabled = true`

I get:  

`override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?)`

`let location  = touch.location(in: self)`

`isUserInteractionEnabled = true`

**Comment by esscbee** [comment]
Fixed in dc35e24.
