### ISSUE TITLE
Swift 3 Syntax issue Creature Class

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#5]
## P3 Creature Class

Appears to be some Swift 3 changes. 

Line 17: `hidden = !isAlive` becomes: `isHidden = !isAlive`

Line 27: `UIColor.clearColor()` becomes: `UIColor.clear`

**Comment by esscbee** [comment]
fixed in 3160fd5
