### ISSUE TITLE
Swift 3 Syntax issue Connecting the Grid

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Game-Of-Life-SpriteKit-Swift3#8]
# P4: Connecting the Grid

The description under Connecting the Grid should read: 

`didMove(to view: SKView)`

The code sample below should read: 

`gridNode = childNode(withName: "gridNode") as! Grid`

**Comment by esscbee** [comment]
fixed in commit 6d31a68f7291ac9954c106c3b6e5c8f0426077fc
